### Álgebra Linear

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7], [8,9]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [5]:
x.dot(y) # equivalente ao np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [6]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [7]:
# podemos utilizar o @ para realizar a multiplicação

x @ np.ones(3)

array([ 6., 15.])

In [12]:
from numpy.linalg import inv, qr

In [13]:
X = np.random.randn(5,5)

In [14]:
X

array([[-0.65510162, -0.38654882,  0.07263483,  2.00975397, -1.47599189],
       [ 0.9000805 , -0.1306248 , -0.02189332,  0.60078139,  0.24135403],
       [ 0.44050904, -1.28536045, -0.73867771,  0.37332903, -0.50562798],
       [-0.10672695, -0.00309582, -0.71696522,  0.10431179, -1.40789922],
       [ 0.3457574 ,  0.38436577, -1.37634085, -1.32052721, -0.02236718]])

In [15]:
mat = X.T.dot(X) # calculo do produto escalar de X com a sua transpposta X.T
mat

array([[ 1.56429008, -0.29732925, -0.79204367, -1.0791016 ,  1.10395623],
       [-0.29732925,  1.96638094,  0.3974513 , -1.84309573,  1.18469173],
       [-0.79204367,  0.3974513 ,  2.95975317,  1.59976282,  1.30120329],
       [-1.0791016 , -1.84309573,  1.59976282,  6.29409692, -3.12746918],
       [ 1.10395623,  1.18469173,  1.30120329, -3.12746918,  4.47514398]])

In [16]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -3.63058660e-17, -1.71564194e-16,
         4.12511259e-17,  6.30485523e-16],
       [ 1.07509350e-15,  1.00000000e+00,  7.78549865e-16,
        -6.98816327e-16, -7.52046858e-17],
       [-1.12153914e-15,  2.05399292e-16,  1.00000000e+00,
         3.31085774e-16,  5.87974689e-16],
       [-1.25022434e-15,  9.24760558e-16, -1.65493518e-15,
         1.00000000e+00, -7.79410931e-17],
       [ 5.86082927e-17, -1.55803527e-16,  3.93987902e-16,
         2.94029601e-16,  1.00000000e+00]])

##### Algumas funções importantes do _numpy.linalg_

```

diag : Devolve os elementos diagonais (ou fora da diagonal) de uma matriz quadrada como um array 1D, ou converte um array 1D em uma matriz quadrada, com zeros fora da diagonal.

dot : Multiplicação de matrizes.

trace : Calcula a soma dos elementos da diagonal.

det : Calcula o determinante da matriz.

eig : Calcula os autovalores (valores próprios) e os autovetores de uma matriz quadrada.

inv : Calcula a inversa de uma matriz quadrada.

pinv : Calcula a psudoinversa de Moore-Penrose de uma matriz.

qr : Calcula a decomposição QR.

svd : Calcula a SVD.

solve : Resolve o sistema linear Ax = b, em que A é uma matriz quadrada. 

lstsq : Calcula a solução de quadrados mínimos para Ax = b

```

In [19]:
X

array([[-0.65510162, -0.38654882,  0.07263483,  2.00975397, -1.47599189],
       [ 0.9000805 , -0.1306248 , -0.02189332,  0.60078139,  0.24135403],
       [ 0.44050904, -1.28536045, -0.73867771,  0.37332903, -0.50562798],
       [-0.10672695, -0.00309582, -0.71696522,  0.10431179, -1.40789922],
       [ 0.3457574 ,  0.38436577, -1.37634085, -1.32052721, -0.02236718]])

In [18]:
# diagonal principal da matriz quadrada

np.diag(X)

array([-0.65510162, -0.1306248 , -0.73867771,  0.10431179, -0.02236718])