<a href="https://colab.research.google.com/github/cantaruttim/Learning_Python/blob/main/Agrupamento_(clustering).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Vai abordar as técnicas não supervisionadas de agrupamento

2.  três dos principais algoritmos de agrupamento:

- K-means

- Agrupamento hierárquico

- DBSCAN

In [1]:
#!pip install plotly --upgrade

In [2]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

### KMeans (Lloyd)

- Seguimentação de mercado
- Encontrar grupos de clientes que irão comprar um determinado produto/notícia/perfil de clientes (Ex: Netflix)
- Análise de redes sociais

1. O algoritmo de agrupamento cria novos dados e não há rótulo.
2. Identifica quando um grupo começa e quando ele termina (nearest mean).


### Cálculo da Distância (_Euclidiana_)

$$D(x,y) = \sqrt{\sum{(xi - yi)²}}$$


### Clusters (+ _Elbow method_)

$$\sqrt{\frac{N}{2}}$$

In [3]:
from sklearn.cluster import KMeans

In [4]:
x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]  
y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

grafico = px.scatter(x = x, y = y)
grafico.show()

In [5]:
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])


base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [6]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [9]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

AttributeError: 'NoneType' object has no attribute 'split'

In [8]:
centroides = kmeans_salario.cluster_centers_
centroides

AttributeError: 'KMeans' object has no attribute 'cluster_centers_'

In [ ]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  22.66666667, 1700.        ],
       [  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ]])

In [ ]:
rotulos = kmeans_salario.labels_
rotulos

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int32)

In [ ]:
grafico1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color=rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [12, 12, 12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()