<a href="https://colab.research.google.com/github/cantaruttim/Learning_Python/blob/main/Agrupamento_(clustering).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Vai abordar as técnicas não supervisionadas de agrupamento

2.  três dos principais algoritmos de agrupamento:

- K-means

- Agrupamento hierárquico

- DBSCAN

In [1]:
#!pip install plotly --upgrade

In [10]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

### KMeans (Lloyd)

- Seguimentação de mercado
- Encontrar grupos de clientes que irão comprar um determinado produto/notícia/perfil de clientes (Ex: Netflix)
- Análise de redes sociais

1. O algoritmo de agrupamento cria novos dados e não há rótulo.
2. Identifica quando um grupo começa e quando ele termina (nearest mean).


### Cálculo da Distância (_Euclidiana_)

$$D(x,y) = \sqrt{\sum{(xi - yi)²}}$$


### Clusters (+ _Elbow method_)

$$\sqrt{\frac{N}{2}}$$

In [11]:
from sklearn.cluster import KMeans

In [12]:
x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]  
y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

grafico = px.scatter(x = x, y = y)
grafico.show()

In [13]:
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])


base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [14]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [17]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

AttributeError: 'NoneType' object has no attribute 'split'

In [8]:
centroides = kmeans_salario.cluster_centers_
centroides

AttributeError: 'KMeans' object has no attribute 'cluster_centers_'

In [ ]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  22.66666667, 1700.        ],
       [  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ]])

In [ ]:
rotulos = kmeans_salario.labels_
rotulos

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int32)

In [ ]:
grafico1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color=rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [12, 12, 12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

### Dados Randômicos

In [18]:
from sklearn.datasets import make_blobs

In [19]:
X_random, y_random = make_blobs(n_samples=200, centers=5, random_state=1)

In [21]:
X_random, y_random

(array([[-1.96576392e+00,  5.23446451e+00],
        [-5.16022348e+00, -7.04217141e+00],
        [-6.17937069e+00, -2.16733539e+00],
        [-7.39138168e+00, -9.49590389e+00],
        [-6.38481234e+00, -8.47302970e+00],
        [-6.26144310e+00, -3.78347905e+00],
        [-2.04278768e+00,  3.07660864e-01],
        [-4.46426086e+00, -4.39451238e+00],
        [-6.40386190e+00, -6.36106990e+00],
        [ 2.42271161e-04,  5.14853403e+00],
        [-5.99212006e+00, -3.91488289e+00],
        [-6.46137477e+00, -3.14560994e+00],
        [-4.10185174e+00, -1.16625450e+00],
        [-1.01341572e+01, -4.07240274e+00],
        [-5.99004766e+00, -2.82631801e+00],
        [-1.14663009e+00,  4.10839703e+00],
        [-1.17104176e+00,  4.33091816e+00],
        [-9.19585147e+00, -3.90678125e+00],
        [-8.30173556e+00, -7.27738918e+00],
        [-7.56309575e+00, -8.46421308e+00],
        [-1.86845414e+00,  4.99311306e+00],
        [-4.22362233e+00, -2.50312346e+00],
        [-1.90838667e+00,  5.861

In [22]:
grafico = px.scatter(x = X_random[:,0], y = X_random[:,1])
grafico.show()

In [23]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

AttributeError: 'NoneType' object has no attribute 'split'